CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(64),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(30),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_customer_email UNIQUE (email),
    CONSTRAINT uk_customer_external_id UNIQUE (external_id)
);

CREATE TABLE restaurant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    code VARCHAR(32) NOT NULL,
    contact_email VARCHAR(255),
    contact_phone VARCHAR(40),
    default_currency VARCHAR(40),
    timezone VARCHAR(60),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_restaurant_code UNIQUE (code),
    CONSTRAINT uk_restaurant_name UNIQUE (name)
);

CREATE TABLE branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    branch_code VARCHAR(32) NOT NULL,
    name VARCHAR(120) NOT NULL,
    address_line VARCHAR(255),
    city VARCHAR(120),
    country VARCHAR(60),
    postal_code VARCHAR(10),
    CONSTRAINT fk_branch_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (id),
    CONSTRAINT uk_branch_code_per_restaurant UNIQUE (restaurant_id, branch_code)
);
CREATE INDEX idx_branch_restaurant ON branch (restaurant_id);

CREATE TABLE loyalty_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(40) NOT NULL,
    customer_id BIGINT NOT NULL,
    restaurant_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    current_points BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_loyalty_account_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT fk_loyalty_account_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (id),
    CONSTRAINT uk_loyalty_account_number UNIQUE (account_number),
    CONSTRAINT uk_loyalty_account_customer_restaurant UNIQUE (customer_id, restaurant_id)
);
CREATE INDEX idx_loyalty_account_customer ON loyalty_account (customer_id);
CREATE INDEX idx_loyalty_account_restaurant ON loyalty_account (restaurant_id);

CREATE TABLE point_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(255),
    rule_type VARCHAR(20) NOT NULL,
    multiplier DECIMAL(7,2) NOT NULL,
    amount_threshold DECIMAL(10,2) NOT NULL,
    base_points INTEGER NOT NULL,
    valid_from DATE,
    valid_until DATE,
    active BOOLEAN NOT NULL,
    CONSTRAINT fk_point_rule_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (id),
    CONSTRAINT uk_point_rule_name_per_restaurant UNIQUE (restaurant_id, name)
);
CREATE INDEX idx_point_rule_restaurant ON point_rule (restaurant_id);

CREATE TABLE reward (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    reward_code VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(255),
    reward_type VARCHAR(20) NOT NULL,
    cost_points INTEGER NOT NULL,
    valid_from DATE,
    valid_until DATE,
    active BOOLEAN NOT NULL,
    CONSTRAINT fk_reward_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant (id),
    CONSTRAINT uk_reward_code_per_restaurant UNIQUE (restaurant_id, reward_code)
);
CREATE INDEX idx_reward_restaurant ON reward (restaurant_id);

CREATE TABLE purchase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loyalty_account_id BIGINT NOT NULL,
    branch_id BIGINT,
    purchase_number VARCHAR(40) NOT NULL,
    total_amount DECIMAL(12,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    purchased_at TIMESTAMP NOT NULL,
    notes VARCHAR(255),
    CONSTRAINT fk_purchase_account FOREIGN KEY (loyalty_account_id) REFERENCES loyalty_account (id),
    CONSTRAINT fk_purchase_branch FOREIGN KEY (branch_id) REFERENCES branch (id),
    CONSTRAINT uk_purchase_number UNIQUE (purchase_number)
);
CREATE INDEX idx_purchase_account ON purchase (loyalty_account_id);
CREATE INDEX idx_purchase_branch ON purchase (branch_id);
CREATE INDEX idx_purchase_occurred_at ON purchase (purchased_at);

CREATE TABLE point_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loyalty_account_id BIGINT NOT NULL,
    entry_type VARCHAR(20) NOT NULL,
    points BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    description VARCHAR(255),
    purchase_id BIGINT,
    point_rule_id BIGINT,
    CONSTRAINT fk_point_ledger_account FOREIGN KEY (loyalty_account_id) REFERENCES loyalty_account (id),
    CONSTRAINT fk_point_ledger_purchase FOREIGN KEY (purchase_id) REFERENCES purchase (id),
    CONSTRAINT fk_point_ledger_rule FOREIGN KEY (point_rule_id) REFERENCES point_rule (id)
);
CREATE INDEX idx_point_ledger_account ON point_ledger (loyalty_account_id);
CREATE INDEX idx_point_ledger_purchase ON point_ledger (purchase_id);
CREATE INDEX idx_point_ledger_rule ON point_ledger (point_rule_id);

CREATE TABLE redemption (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loyalty_account_id BIGINT NOT NULL,
    reward_id BIGINT NOT NULL,
    ledger_entry_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    redeemed_at TIMESTAMP NOT NULL,
    notes VARCHAR(255),
    points_spent BIGINT NOT NULL,
    CONSTRAINT fk_redemption_account FOREIGN KEY (loyalty_account_id) REFERENCES loyalty_account (id),
    CONSTRAINT fk_redemption_reward FOREIGN KEY (reward_id) REFERENCES reward (id),
    CONSTRAINT fk_redemption_ledger FOREIGN KEY (ledger_entry_id) REFERENCES point_ledger (id),
    CONSTRAINT uk_redemption_ledger UNIQUE (ledger_entry_id)
);
CREATE INDEX idx_redemption_account ON redemption (loyalty_account_id);
CREATE INDEX idx_redemption_reward ON redemption (reward_id);
