CREATE TABLE reward_redemption (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reward_id BIGINT NOT NULL,
    loyalty_account_id BIGINT NOT NULL,
    redemption_code VARCHAR(20) NOT NULL,
    redeemed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    redeemed_at TIMESTAMP NULL,
    CONSTRAINT fk_reward_redemption_reward FOREIGN KEY (reward_id) REFERENCES reward (id),
    CONSTRAINT fk_reward_redemption_account FOREIGN KEY (loyalty_account_id) REFERENCES loyalty_account (id),
    CONSTRAINT uk_reward_redemption_code UNIQUE (redemption_code)
);

CREATE INDEX idx_reward_redemption_account ON reward_redemption (loyalty_account_id);
CREATE INDEX idx_reward_redemption_reward ON reward_redemption (reward_id);
